[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$SMl57/2f835vzVkr5ZxT6g$ZwMeSOQ9kldo4cPT.JBXhkHQesrYu/Hj3Um1E3NcH6QiQIUtjrqU2gFBuk81Tt0Sh4dYqIXyLIF/zY76/NeLcw
db_host = postgres
db_port = 5432
db_user = odoo
db_password = odoo123
log_level = info

